[package]
name = "clexp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
color-eyre = "0.6.5"
crossterm = "0.27"
ratatui = "0.26"
chrono = { version = "0.4", features = ["serde"]}
